import { fileURLToPath } from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core';
import { drizzle as drizzleNodePg } from 'drizzle-orm/node-postgres';
import { migrate as migrateNodePg } from 'drizzle-orm/node-postgres/migrator';
import { drizzle as drizzlePglite } from 'drizzle-orm/pglite';
import { migrate as migratePglite } from 'drizzle-orm/pglite/migrator';
import { Pool } from 'pg';
import { positiveNumberEnv } from '../common/env.js';
import * as schema from './schema.js';

/** The common Drizzle surface both drivers implement; services never see which one is behind it (ADR-0003). */
export type Db = PgDatabase<PgQueryResultHKT, typeof schema>;

export interface DatabaseHandle {
  db: Db;
  /** Which driver opened the database — reported by /api/health so a demo never passes for a deployment. */
  driver: 'pglite' | 'postgres';
  close(): Promise<void>;
}

// Generated by `npm run db:generate -w api`. Same relative depth from src/database and dist/database.
const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));

/** Session-level advisory lock that serializes migrations across API instances (Cycle Audit 3). */
const MIGRATION_LOCK_KEY = 727_274_001;

/**
 * Opens the database and applies the committed migrations so every environment runs the same schema.
 * - `SUPPORT_DATABASE_URL` set (PH-8.2, BL-019): a PostgreSQL server through a `pg` pool — deployments and the
 *   `test:pg` runs; `dataDir` is ignored.
 * - otherwise embedded PostgreSQL (PGlite): in memory when `dataDir` is undefined, persisted to that directory
 *   otherwise — development and the fast test path.
 */
export async function createDatabase(dataDir?: string, url: string | undefined = process.env.SUPPORT_DATABASE_URL): Promise<DatabaseHandle> {
  if (url && url.trim() !== '') {
    const pool = new Pool({
      connectionString: url.trim(),
      // At least 2: the migration lock holds one connection while the migrator uses another.
      max: Math.max(2, positiveNumberEnv('SUPPORT_DB_POOL_MAX', 10)),
      connectionTimeoutMillis: 10_000,
    });
    // An idle client that loses its connection emits 'error' on the pool; unhandled, it would crash the process.
    pool.on('error', (error) => console.error('PostgreSQL pool: idle client error —', error.message));
    const db = drizzleNodePg({ client: pool, schema });
    // Drizzle's migrator creates its schema and reads its journal without a lock; two instances starting together
    // raced on it (the c09c569 CI failure). The advisory lock makes the second one wait and then find nothing to do.
    const lock = await pool.connect();
    try {
      await lock.query('SELECT pg_advisory_lock($1)', [MIGRATION_LOCK_KEY]);
      await migrateNodePg(db, { migrationsFolder: MIGRATIONS_FOLDER });
    } finally {
      await lock.query('SELECT pg_advisory_unlock($1)', [MIGRATION_LOCK_KEY]).catch(() => undefined);
      lock.release();
    }
    return { db: db as unknown as Db, driver: 'postgres', close: () => pool.end() };
  }
  const client = dataDir ? new PGlite(dataDir) : new PGlite();
  await client.waitReady;
  const db = drizzlePglite({ client, schema });
  await migratePglite(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return { db: db as unknown as Db, driver: 'pglite', close: () => client.close() };
}

/** PostgreSQL unique-violation detector; Drizzle wraps driver errors, so look one level down too. */
export function isUniqueViolation(error: unknown): boolean {
  const code = (error as { code?: unknown; cause?: { code?: unknown } } | null)?.code
    ?? (error as { cause?: { code?: unknown } } | null)?.cause?.code;
  return code === '23505';
}
