import { fileURLToPath } from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import { drizzle, type PgliteDatabase } from 'drizzle-orm/pglite';
import { migrate } from 'drizzle-orm/pglite/migrator';
import * as schema from './schema.js';

export type Db = PgliteDatabase<typeof schema>;

export interface DatabaseHandle {
  db: Db;
  close(): Promise<void>;
}

// Generated by `npm run db:generate -w api`. Same relative depth from src/database and dist/database.
const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));

/**
 * Embedded PostgreSQL (PGlite): in memory when `dataDir` is undefined, persisted to that directory
 * otherwise. Migrations are applied on open so every environment runs the committed schema.
 * Deployed environments swap this factory for a PostgreSQL server driver (ADR-0003).
 */
export async function createDatabase(dataDir?: string): Promise<DatabaseHandle> {
  const client = dataDir ? new PGlite(dataDir) : new PGlite();
  await client.waitReady;
  const db = drizzle({ client, schema });
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return { db, close: () => client.close() };
}

/** PostgreSQL unique-violation detector; Drizzle wraps driver errors, so look one level down too. */
export function isUniqueViolation(error: unknown): boolean {
  const code = (error as { code?: unknown; cause?: { code?: unknown } } | null)?.code
    ?? (error as { cause?: { code?: unknown } } | null)?.cause?.code;
  return code === '23505';
}
